stages:
  - compile
  - package
  - release


compile:
  stage: compile
  image: debian:stable-slim
  before_script: 
  - /bin/sh ./toolchain.sh
  script:
  # Build for AMD64
  - cmake -S . -B build-amd64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=toolchain-x86-64.cmake
  - cmake --build build-amd64

  # Build for ARM64
  - cmake -S . -B build-arm64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=toolchain-arm64.cmake
  - cmake --build build-arm64

  artifacts:
    when: on_success
    expire_in: "30 days"
    paths:
      - bin

debian_package:
  stage: package
  rules: 
  - if: $CI_COMMIT_TAG
  needs:
  - compile
  image: debian:stable-slim
  parallel:
    matrix:
      - arch: [ "aarch64", "amd64" ]
  script:
    - ./deb_package.sh minit "${CI_COMMIT_TAG}" "${CI_COMMIT_TAG}" "$arch"
