name: Build Minit

on: 
  push:
    branches:
      - main

jobs:
  build_binaries:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ x86-64, aarch64, riscv64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: setup toolchain
        run: |
          sudo apt-get install -y gcc-${{ matrix.arch }}-linux-gnu g++-${{ matrix.arch }}-linux-gnu build-essential cmake
      - name: run cmake
        run: |
          cmake -S . -B build-${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=toolchian-${{ arch }}.cmake
          cmake --build build-${{ matrix.arch }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: minit-${{ matrix.arch }}-${{ github.ref_name }}
          path: output/test/code-coverage.html