name: Semantic Release

on: 
  push:
    branches:
    - main
    - dev/*
    - feature/*
    - hotfix/*

jobs:
  build_binaries:
    name: Build Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ x86-64, aarch64, riscv64 ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: setup toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-${{ matrix.arch }}-linux-gnu g++-${{ matrix.arch }}-linux-gnu build-essential cmake
      - name: run cmake
        run: |
          cmake -S . -B build-${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=toolchain-${{ matrix.arch }}.cmake
          cmake --build build-${{ matrix.arch }}
          sha256sum bin/minit > bin/minit.sha256sum
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: minit-${{ matrix.arch }}
          path: bin/*
          retention-days: 1

  semantic-release:
    needs: build_binaries
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    name: Semantic Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Prepare prerelease semantic
        if: github.ref != 'refs/heads/main'
        run: mv .releaserc.prerelease.yaml .releaserc.yaml
      - name: Download build artifacts
        uses: actions/download-artifact@v5
        with: 
          path: bin
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with: 
          semantic_version: 17
          extra_plugins: |
            @semantic-release/changelog@5"
            @semantic-release/exec@5"
            @semantic-release/git@9"
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}